name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal

env:
  REGISTRY: repositorio.azurecr.io
  IMAGE_NAME: exploreapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Construir y etiquetar la imagen Docker
        run: |
          # Construimos la imagen con la etiqueta "latest" y una con el ID del commit
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Subir la imagen a Azure Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}